name: CI - Build and Test

on:
  push:
    branches:
      - '**'
    pull_request:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Validar Projeto (build)
        run: mvn clean install -DskipTests

      - name: Rodar Testes
        run: mvn test